# site settings
title: Test page
subtitle: by HTML5 UP
email: jeff.barlow.spady@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: https://github.com/Jeff-Barlow-Spady/https-jeff-barlow-spady.github.io/tree/main
#author:
#street_address: 1234 Somewhere Road
#city: Nashville
#state: TN
#zip_code: 55555
#country: United States of America
#phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
- generic.md
- elements.md
- allposts.md
- landing.md
